# Starter pipeline






- task: AzureRmWebAppDeployment@4

  inputs:

    ConnectionType: 'AzureRM'

    azureSubscription: 'Microsoft Azure Enterprise - CoE(MS)(15c9a3ed-7da9-401a-8533-57039223ff04)'

    appType: 'webApp'

    WebAppName: 'testingapppoc'

    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'







# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
